import socket
import sys
from time import *
from datetime import datetime
import os
os.system("clear")
#############################################
print ("\033[0;31m====================================> welcome <====================================")
###########################################
def banner():
    print("")
sleep(.2)
print("\033[0;32m                            `.--://++ooosssssssooo+//:-.``")
sleep(.2)
print("                       .:+shmmNNNNNNNNNNNNNNNNNNNNNNmmmddhhys+/-.")
sleep(.2)
print("                   ./sdmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmddddhhhys+:.")
sleep(.2)
print("                -+hdmNNNNNNNNMMMMMMMMMMMNNNNNNNNNNNNNNmmmmddddhhhyyso+:.")
sleep(.2)
print("             `:ydmmNNNNNNNNMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmddddhhhhhyysso+/")
sleep(.2)
print("            .sdmmmmmmNNNNNNNNMMMMMMMMMMMMMMMNNNNNNNNNNNmmmmdddhhyysyssoo+:")
sleep(.2)
print("            odmmmmmmNNNNNNNNNNNMMMMMMMMMMMMMNNNNNNNNNNNNNNmmmmddhhysssso+/`")
sleep(.2)
print("            ydmddmNNNNNNNMMMMMMNNMMMMMMMMMMNNNNNNNNNNNNmdhyssoosssyysoso+/.")
sleep(.2)
print("            `hddmdyo+/:::/oydmNNMMMNMMMMMMMMNNNNNNNNdyo::-.``..-----:+sooo+.")
sleep(.2)
print("           -hdh+:/+oo+/:-:/+ohmmmNMMNMMMMMMMMMNNds:.` `.:+syhddddhys+:+oo+-")
sleep(.2)
print("           :hhoymNNNNNNNmdhhhdy+::omMMMMMMMMMNh/.  `.:shmNNNNNNmmddhyyooo+-")
sleep(.2)
print("           /hdmNNNNMMMMMMMMMNNs:.``oMMMMMMMMMs```-oydNNNNNNNMNNNmmdhhysoo+:")
sleep(.2)
print("           /hmmNNNMMMMMMMMMMMNNNdyymMMMMMMMMNh/+ydmNNNNNNNNNNNNmmmddhysso+:")
sleep(.2)
print("           ohmmNNNMMMMMMMMMNNNNNNNNMMMMMMMMMNmmddNNNNNNNNNNNNNmmmdddhysso+/`")
sleep(.2)
print("          `sdmmNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNmddNNNNNNmmddddddmmmdddhyssoo/`")
sleep(.2)
print("          `hddmNNNNNmhs+//+oshmNNNNMMMMMMMMMNmdmNNNdy+:..````.:+yddhysssso/.")
sleep(.2)
print("          -hmmmmNNm/`      ```.:omMMMMMMMMMMNmmmmm/`            .hdhyyysso+.")
sleep(.2)
print("          -dmmmNNNm/.```````..:/+mMMMMMMMMMNNmddmmysso+/:::::/+shdddhyysso+`")
sleep(.2)
print("          -dmmmNNNNNNmddhddmNMMMMMMMMMMMMMMNmmdmmmmNNNNNNNNNmmmmmmmddhyso+/`")
sleep(.2)
print("         -hmmNNNNNNNNMMMMMMMMNNMMMMMMMMMNNNmmmmmdmmNNNNNNNNNNNmmmdddhhyso/`")
sleep(.2)
print("          -dNNNNNNNNNNMMMMMMMMMMMMMMMMMMMNNNmmmmmddmmNNNNNNNNmmmmdddhhhhyo:`")
sleep(.2)
print("          .mNNNmmmmNNNMMMMMMMMMMMMMMMMMMMMNNmmmmmddmmNNNNNNNNNmmddhhhhhhso-")
sleep(.2)
print("           hNNmdmmmNNNMMMMMMMMMMMMMMMMMMMMNNmmmmmdddmmmNNNNNNNNmddhyyyyso/.")
sleep(.2)
print("           /dmmdmmmmNNMMMMMMMMMMMMMMMMMMMMMNNmmmmddddddmmNNNNmmddhhyyyso+:.")
sleep(.2)
print("           .ydmmmmmmNNNMMMMNNNNMMMMMMMMMMMMMNmmmmddddhhhdmmmmmmddhhyyso++:`")
sleep(.2)
print("            odmmmmmNNNNNNNNNNNMMMMMMMMMMMMMMNmmdddddddddddddddddhyssssso/-")
sleep(.2)
print("            :ymNmdyhmNNNNNNNMMNNNNNMMMMMMMMMNmdddhhdhdddmmmmmddhy..shmy/:`")
sleep(.2)
print("            `shNMN:`hNNNNNMMMMMNNmNNNNMMMNNmddddhyhddmmmmmmmmddh. +ydd+/.")
sleep(.2)
print("             /hmNNm-.hNNMMMMMMMMMMNMNy+osso+:-+dddmmmmmmmmmmmdo.`+shds/:")
sleep(.2)
print("             `ydmMNm:`+dNMMMMMMMMMNdo----:-```.:sdmNNmmmmmmho-`.oyyds+/.")
sleep(.2)
print("              +hdmMNm+``:shdmmddho::-:-/ymdo.```.-+ssyyys+:.`.+syyhs+/:`")
sleep(.2)
print("              -hddmNNNdo:...--.....:--odNNNmh:``..````...-:/syyyyhs+//.")
sleep(.2)
print("              /dddmNNNNNmdhyso++:::/sdmmmmddy/..--+osyyhddhysyhhs++/.")
sleep(.2)
print("                /hddmNMNmmNNMMNNNmyysssssssssssyyyhmmmdddhysshdyo+/:`")
sleep(.2)
print("                 .ohddmNNmmmNNNNMMMMMMMMMMMNNNNNNNNmddhyysssddso+/.")
sleep(.2)
print("                   -sddmNNmmmNNmNNNNNNmmmmmmddddmddhhhhyysydho++:`")
sleep(.2)
print("                     :yddmNNmmNNNNNNNNy--.....odmmmddhhysyhyo+/.")
sleep(.2)
print("                      `:ydmmNmNNNNNNNNN.     .ymmmmddhyyhyso+:`")
sleep(.2)
print("                         `+hmmNNNNNMMMMN/`` ``-hmNNmmdhyyyoo/")
sleep(.2)
print("                           .odmmmNNNMMMN+`````:hmNNmdhysso+-")
sleep(.2)
print("                            .smmNNNNMNNs`` ``:hmmmdhysso:`")
sleep(.2)
print("                              :ymNNNNNNy     :hmmmdhso/`")
sleep(.2)
print("                               `/hmNNNNd     :hmddys/.")
sleep(.2)
print("                                 `/hdmmm.    /yhys/.")
sleep(.2)
print("                                    -/os+    :/:.`")
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
print("                                     \033[0;31m>>>RMX-iraq<<<")
###########################################
###########################################
###########################################
ip = input("======> Enter your ip <======: ")
t1=datetime.now()
print ("Scanning.. %s please with.."%ip)
sleep(1)
#############################################
try:
	for port in range(1,6653):
		s=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
		if (s.connect_ex((ip,port))==0):
			try:
				serv=socket.getservbyport(port)
			except socket.error:
				serv="Unknown Service"
			print("port %s open service: %s "%(port,serv))
		t2=datetime.now()
		t3=t2-t1
	print("Scanning Completed on%s"%t3)
except KeyboardInterrupt:
		print("canser good bay")
